### ISSUE TITLE
selecting articles

### ISSUE THREAD

**Issue by schunka** [tschinz/tt-rss_reeder_theme#11]
In a default themes, and in general, TT RSS offers some advanced managing tools for articles, which are disabled in this theme. Could you somehow reenable it?
What I have in mind is normally you can select multiple articles and perform some action above it, like mark as read/unread/starred/... this is impossible in this theme, which takes away a lot of useful functionality from TT RSS.
This theme is really great and it would be shame to cripple it by omitting those features.

**Comment by tschinz** [comment]
Hello schunka,

I know that not all features of ttrss are enabled in this theme. The multiselection and actions are disabled because they are not much used and doesn't give a nice user experience anymore (at least for me). Therefore these features won't be enabled.
I'm sorry thats one of the reasons I created this theme.
You can look at the css file and enable them. Search for /* Remove functions I don't want */

Cheers
