### ISSUE TITLE
Combined mode

### ISSUE THREAD

**Issue by balajeek** [tschinz/tt-rss_reeder_theme#25]
Beautiful theme, exactly what i needed.  Just got tt-rss installed and this theme and wondering how can i make the combined theme by hiding the feed titles like how its show in the picture.  I don't see the little 3dash button on the far left though.

**Comment by tschinz** [comment]
Hello balajeek.
the combined mode can be enabed in the Preferences.
![image](https://user-images.githubusercontent.com/1192968/32209902-02e9f232-be0b-11e7-899a-cfcf2bd5b463.png)
The 3 dash buttons are not there somehow they vanished since a newer release of tt-rss I'll have to investigate. I don't have much free time so don't expect a result soon. Feel free to look at the problem yourself.

tschinz

**Comment by tschinz** [comment]
Hello balajeek,

ok I've just looked at the problem. Firsts of all you need to install and activate the plugin called toggle_sidebar. And then there were still some html tags which did change. I fixed it in 27417607f34837b541dd0907e15fe69617f52701. Should be working now.

let me know if it's fixed and please close the issue

**Comment by balajeek** [comment]
Yes, I can confirm it works now.
I re-downloaded the reeder.css and also enabled the toggle-sidebar plugin
I am able to see the 3dash button and clicking on it shows/hides side bar.

I was a feedly user until yesterday and setup this tt-rss and was disappointed the way it looked, then I realized its barebone and customize css option exist and found this reeder theme which made a whole lot of difference.  Thank you so much for taking time in developing and supporting.

![screen shot 2017-10-31 at 10 01 48 am](https://user-images.githubusercontent.com/19213088/32227760-a086bef0-be22-11e7-87e2-dee66b39d015.png)

(still i need for find why the img didn't come thru, just only on this feed, could be wrong with the feed itself which is slickdeals/hotdeals)
