### ISSUE TITLE
bold and align broken on 18.12

### ISSUE THREAD

**Issue by theguly** [tschinz/tt-rss_reeder_theme#31]
hi there, looks like 18.12 brokes (at least) two things:
- column alignment, see screenshot
![screen shot 2018-12-03 at 10 38 06](https://user-images.githubusercontent.com/1745802/49365753-dcf93d00-f6e7-11e8-8ea0-d7aacdc1de05.png)

- font-weight: bold is not present in Unread content, every hl-content is now non-bold

do you still support this plugin against new TTRSS releases?

**Comment by tschinz** [comment]
Hello,
no I don't use TTRSS anymore, for the moment this theme is community driven, if you fix is you can send me a pull request and I will integrate it.
It is very much annoying that TTRSS without changing big stuff is with each release redefining stuff which would not be needed. It was for me too annoying to keep uptodate.

Feel free to fix and send me a pull request

**Comment by theguly** [comment]
i fixed the bold stuff but i'm not into CSS enough to fix the other one, and honestly who cares about bold when you have a tetris of titles/feeds/icons? :)
i'll try to ask TTRSS devs but if i got your point i'll have to change theme/agg.

anyway thanks for creating this theme long ago.

**Comment by jonathanherrmannengel** [comment]
@tschinz (@theguly) 

I'm sorry to disappoint you, but later commits to TT-RSS 18.12 break even more elements of your theme. If you use a recent commit of TT-RSS 18.12 and just change the supported-version annotation it will look like this:

![18 12_no_mods](https://user-images.githubusercontent.com/38504994/50036393-f021dc00-0008-11e9-8fb7-ff3791299955.jpg)

This is a quote from the feedly theme (https://github.com/levito/tt-rss-feedly-theme):

> Feedly theme for Tiny Tiny RSS 1.15 – 18.8. This theme will probably not be updated to support newer versions of tt-rss.
 The latest fully working tt-rss commit of version 18.8 is da1a3c2. After that, things start to fall apart.
If you are on version 18.12 or newer, this theme will not work. Until tt-rss commit f679ec2, you can try the branch v18.12. Later commits include a new dojo base theme and will break badly!

My fork of your Reeder Theme does now support TT-RSS 18.12 (older as well as newer commits with a focus on the newer ones). Still it was not possible to transfer the full beauty of your original Reeder Theme due to the breaking changes in the middle of TT-RSS 18.12 development. Furthermore older versions like TT-RSS 18.8 are not supported by the recent commits to my fork anymore.

This is how your original theme (18.8) looks like:

![18 8_split](https://user-images.githubusercontent.com/38504994/50036896-e1d5bf00-000c-11e9-8ddd-f9f1a98f4d71.jpg)
![18 8_combined](https://user-images.githubusercontent.com/38504994/50036897-e1d5bf00-000c-11e9-8f5b-991dcdb3405a.jpg)


This is how my forked theme (18.12 / older commits of TT-RSS 18.12) looks like. As you see your modified image resources coudn't be copied, because newer commits of TT-RSS 18.12 changed the image resources to a icon font and this font would break, if I continued supporting these image resources:

![18 12_old_split](https://user-images.githubusercontent.com/38504994/50036904-f0bc7180-000c-11e9-8b0e-a3292fbeb0ba.jpg)
![18 12_old_combined](https://user-images.githubusercontent.com/38504994/50036905-f0bc7180-000c-11e9-99fb-0bb0f55b98c4.jpg)


This is how my forked theme (18.12 / newer commits of TT-RSS 18.12) looks like:

![18 12_new_combined](https://user-images.githubusercontent.com/38504994/50036630-712da300-000a-11e9-94fc-feb06ab28386.jpg)
![18 12_new_split](https://user-images.githubusercontent.com/38504994/50036914-0336ab00-000d-11e9-9841-533cbb36547d.jpg)


As you see my forked theme is not as beautiful as your original theme anymore.. And as I stated it does not support TT-RSS versions prior to 18.12 anymore...

@tschinz: If you wish I can create a pull request, but personally I do not think this is fitting your original theme well enough. There are some improvements like a mobile version as well, but I still think it won't fit.
@theguly: If you wish you may use my forked theme (of course, everyone may use it (-; ) and if you want you may improve it as well.

Sincerely
Jonathan

**Comment by tschinz** [comment]
Hi Jonathan,
thanks for all your investigations. It is unfortunate that ttrss is changing so much without big improvements.
I tried to create a theme as much unlinked from ttrss as possible but as you saw it is quite difficult. I tried talking to the creator of ttrss to know in advance when something breaking will be introduced, but that is not possible.
All this is one reason I abandon this project. I'm sorry for all using my theme and ttrss. 
I don't think a pullrequest is needed here. 

Thanks anyway for your work.

**Comment by machsix** [comment]
It's a pity that you don't maintain this project anymore and thanks for your great work!

For those who want to recover the theme shipped with ttrss but couldn't do it with webui, you can login to your postgresql database and execute the following command:
```
update ttrss_user_prefs set value='base.css' where pref_name='USER_CSS_THEME';
```

**Comment by Boshishengworkh** [comment]
If you had just applied the reeder_themes to your latest ttrss,  the webpage then cracked so that you even cannot find the buttons. Look here! one method helps you out.
First, enter into ttrss in docker.    use order: docker exec -it ttrss-ID bash  (bash changes into sh when using alpine)
![image](https://user-images.githubusercontent.com/52349597/83494404-cc966e00-a4e8-11ea-91f3-06bb5ce02024.png)
then, find the reeder_theme location, just remove it.  use order: rm -r
when you remove the working reeder.css , the ttrss will back to the normal webpage.
